site_name: Legacy Roleplay
site_description: 'Wet en regelgeving van Legacy Roleplay'
site_author: 'Legacy Roleplay'
copyright: Copyright &copy; 2024-2025 Legacy Roleplay
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  primary: green
#   features:
#     - navigation.tabs
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference
        language: nl
        
